import pygame
import random
from perlin_noise import PerlinNoise

pygame.init()

# Display and Window Settings
START_FULLSCREEN = False
MONITER_RES = pygame.display.Info().current_w, pygame.display.Info().current_h
MIN_WIN_RES = 1280, 720
MAX_WIN_RES = 2560, 1440
WIN_RES = MONITER_RES if START_FULLSCREEN else MIN_WIN_RES
PLAYABLE_AREA_SIZE = 3840, 2160
REN_RES = 640, 360

# Player Settings
PLAYER_RES = 64, 64
PLAYER_VEL = 200
PLAYER_DAMAGE = 30
PLAYER_HEALTH = 100
PLAYER_STAMINA = 100
PLAYER_ACCELERATION = 600
PLAYER_OFFSET_X1, PLAYER_OFFSET_X2 = 0, 0
PLAYER_OFFSET_Y1, PLAYER_OFFSET_Y2 = 0, 0
PLAYER_NAME = "Player"

# Weapon Settings
AK47_RES = 50, 18
AK47_VEL = 700
AK47_SPREAD = 3
AK47_RELOAD_TIME = 2
AK47_FIRE_RATE = 0.1
AK47_CLIP_SIZE = 30
AK47_LIFETIME = 3
AK47_LIFETIME_RANDOMNESS = 0.2
AK47_DAMAGE_DROP_OFF = 2
AK47_DAMAGE = 30
AK47_DISTANCE = -2
AK47_HEALTH = 1

SHOTGUN_RES = 32, 32
SHOTGUN_VEL = 700
SHOTGUN_SPREAD = 15
SHOTGUN_RELOAD_TIME = 1.5
SHOTGUN_FIRE_RATE = 0.8
SHOTGUN_CLIP_SIZE = 8
SHOTGUN_LIFETIME = 0.5
SHOTGUN_LIFETIME_RANDOMNESS = 0.2
SHOTGUN_DAMAGE_DROP_OFF = 5
SHOTGUN_DAMAGE = 50
SHOTGUN_DISTANCE = -2

MINIGUN_RES = 38, 20
MINIGUN_VEL = 800
MINIGUN_SPREAD = 10
MINIGUN_RELOAD_TIME = 10
MINIGUN_FIRE_RATE = 0.01
MINIGUN_CLIP_SIZE = 100
MINIGUN_LIFETIME = 2
MINIGUN_LIFETIME_RANDOMNESS = 0.2
MINIGUN_DAMAGE_DROP_OFF = 1
MINIGUN_DAMAGE = 15
MINIGUN_DISTANCE = -10

# Player Gun Settings
PLAYER_GUN_DISTANCE = -2
PLAYER_GUN_RES = 40, 40
PLAYER_GUN_SPREAD = 20
PLAYER_BULLET_RES = 24, 24
PLAYER_BULLET_FRICTION = 2
PLAYER_BULLET_DAMAGE = 20
PLAYER_BULLET_LIFETIME = 0.8
BULLET_LIFETIME_RANDOMNESS = 0.2
PLAYER_BULLET_SPEED = 700
PLAYER_BULLET_RATE = 0.1
PLAYER_BULLET_ANIMATION = 15
PLAYER_GUN_SPREAD_TIME = 2

# Enemy Settings
ENEMIES_SPAWNING = False
ENEMY_RES = 32, 36
ENEMY_VEL = 320
ENEMY_DAMAGE = 20
ENEMY_HEALTH = 100
ENEMY_SPAWN_RATE = 1
ENEMY_BULLET_RES = 10, 10
ENEMY_BULLET_DAMAGE = 10
ENEMY_BULLET_LIFETIME = 1000
ENEMY_BULLET_SPEED = 700
ENEMY_STOPPING_DISTANCE = 25
ENEMY_NAME = "Enemy"
ENEMY_SCREEN_SHAKE_DURATION = 0.5
ENEMY_SCREEN_SHAKE_MAGNITUDE = 4
ENEMY_STEERING_STRENGTH = 0.8
ENEMY_FRICTION = 0.2
MAX_ENEMIES = 50

# Animation Settings
ANIMATION_SPEED = 5
MAIN_MENU_ANIMATION_SPEED = 15
BORDER_ANIMATION_SPEED = 10

# UI Settings
BUTTONS_SIZE = 1.1
FONT = "Assets/Font/font2.ttf"
MOUSE_RES = 13, 13

# Window Settings
WINDOW_MAX_OFFSET = 0.3
WINDOW_LERP_SPEED = 5
WINDOW_DEADZONE = 3
WINDOW_SHAKE_SPEED = 200
WINDOW_MOUSE_SMOOTHING = 10, 10
WINDOW_SHAKE_DIRECTIONS = 1, 1
WINDOW_MOUSE_SMOOTHING_AMOUNT = 50

# Button Settings
PLAY_BUTTON_NAME = "PLAY"
PLAY_BUTTON_POS = 200, 240
PLAY_BUTTON_RES = 46, 15
PLAY_BUTTON_AXIS = "y"
PLAY_BUTTON_AXISL = "max"

QUIT_BUTTON_NAME = "QUIT"
QUIT_BUTTON_POS = 280, 240
QUIT_BUTTON_RES = 46, 15
QUIT_BUTTON_AXIS = "y"
QUIT_BUTTON_AXISL = "max"

EASY_BUTTON_NAME = "EASY"
EASY_BUTTON_POS = 200, 190
EASY_BUTTON_RES = 46, 15
EASY_BUTTON_AXIS = "y"
EASY_BUTTON_AXISL = "max"

MEDIUM_BUTTON_NAME = "MEDIUM"
MEDIUM_BUTTON_POS = 200, 150
MEDIUM_BUTTON_RES = 46, 15
MEDIUM_BUTTON_AXIS = "y"
MEDIUM_BUTTON_AXISL = "max"

HARD_BUTTON_NAME = "HARD"
HARD_BUTTON_POS = 280, 190
HARD_BUTTON_RES = 46, 15
HARD_BUTTON_AXIS = "y"
HARD_BUTTON_AXISL = "max"

STORE_BUTTON_COOLDOWN = 0.5

# Settings UI
FULLSCREEN_BUTTON_POS = 240, 170
BRIGHTNESS_SLIDER_POS = 360, 235
NEW_QUIT_BUTTON_POS = 240, 215
RESUME_BUTTON_POS = 240, 135
FPS_SLIDER_POS = 360, 180

SETTINGS_BUTTON_SPEED = 900
SETTINGS_BUTTON_FRICTION = 300

# HUD Settings
HEALTH_BAR_POS = 135, 95
STAMINA_BAR_POS = 170, 95
OUSTIDE_BARS_RES = 106, 19
FPS_POS = 150, 74
TIME_POS = 150, 74
FPS_AND_TIME_SIZE = 15

# Key Bindings
FULLSCREEN_KEY = pygame.K_F11
TOGGLE_FPS_KEY = pygame.K_F12
ESCAPE_KEY = pygame.K_F10
UNGRAB_KEY = pygame.K_ESCAPE

# Misc Settings
START_WITH_FPS_AND_TIME = False
FPS_AND_TIME_COOLDOWN = 0.5
FULLSCREEN_COOLDOWN = 0.5
SETTINGS_COOLDOWN = 0.5
SETTINGS_DARKENING = (12, 12, 12)

MAX_DARKNESS = 2.5
MAX_BRIGHTNESS = 0.5
INITIAL_BRIGHTNESS = 50

# Difficulty Multipliers
EASY_PLAYER_HEALTH_MULTIPLYER = 1.5
HARD_PLAYER_HEALTH_MULTIPLYER = 0.7
MEDIUM_PLAYER_HEALTH_MULTIPLYER = 1

EASY_PLAYER_DAMAGE_MULTIPLYER = 1.1
HARD_PLAYER_DAMAGE_MULTIPLYER = 0.9
MEDIUM_PLAYER_DAMAGE_MULTIPLYER = 1

EASY_ENEMY_MULTIPLYER = 0.7
HARD_ENEMY_MULTIPLYER = 1.3
MEDIUM_ENEMY_MULTIPLYER = 1

# Particle Effects
BULLET_SPARK_SPREAD = 10
BULLET_SPARK_SIZE = 0.6
BULLET_SPARK_COLOUR = (255, 0, 0)
BULLET_SPARK_AMOUNT = 3

GUN_SPARK_SPREAD = 5
GUN_SPARK_SIZE = 0.3
GUN_SPARK_COLOUR = (255, 255, 255)
GUN_SPARK_AMOUNT = 3

# Tilemap Settings
TILEMAP_SIZE = 16
SPATIAL_GRID_SIZE = 300

# Perlin Noise Settings
PERLIN_OCTAVES = 3
PERLIN_SEED = random.randint(0, 100000)
perlin = PerlinNoise(octaves=PERLIN_OCTAVES, seed=PERLIN_SEED)
